name: Enterprise Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Validation
        run: echo "Build successful"

      - name: Deployment Validation
        run: echo "Deployment successful"
